apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight2024-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight2024
  template:
    metadata:
      labels:
        app: flight2024
    spec:
      containers:
        - name: flight2024-app
          image: flight2024-app:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/flight2024"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                 name: mysql-config
                 key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: flight2024-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: flight2024
  type: LoadBalancer